.\" Copyright [YEAR] [AUTHOR] ([EMAIL])
.\" MIT LICENSE
.\"
.TH [NAME_ALL_CAPS] 3 [yyyy-MM-dd] "ZC" "Linux Programmer's Manual"
.SH NAME
[NAME] \- [BRIEF]
.SH SYNOPSIS
.B #include <[Z_HEADER_H]>
.P
.BI "[RETURN_TYPE] [NAME]();
.SH DESCRIPTION
.SS PARAMETERS
.SH RETURN VALUE
.SH ERROR
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR [NAME] ()
T}	Thread safety	MT-Safe
.TE
.SH EXAMPLE
.SH SEE ALSO
