.\" Copyright [YEAR] [AUTHOR] ([EMAIL])
.\" MIT LICENSE
.\"
.TH ZVEC_COUNT 3 [yyyy-MM-dd] "ZC" "Linux Programmer's Manual"
.SH NAME
zvec_count \- number of elements between the given iterators.
.SH SYNOPSIS
.B #include <zvec.h>
.P
.BI "int32_t zvec_count(zvec_t " this ",
.BI "zvec_it " begin ", zvec_it " end ");
.SH DESCRIPTION
.SS PARAMETERS
.SH RETURN VALUE
.SH ERROR
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR zvec_count ()
T}	Thread safety	MT-Safe
.TE
.SH EXAMPLE
.SH SEE ALSO
