.\" Copyright 2022 Yu Ze (pseudoc@163.com)
.\" MIT LICENSE
.\"
.TH ZVEC_NEW 3 2022-01-29 "ZC" "Linux Programmer's Manual"
.SH NAME
zvec_new \- create instance of opaque type
.IR zvec_t .
.SH SYNOPSIS
.B #include <zvec.h>
.P
.BI "zvec_t* zvec_new(size_t " soe ");
.SH DESCRIPTION
The
.BR zvec_new ()
function allocates
block of memory for the container,
which uses
.BR malloc ()
to allocate related memory blocks
and its initial capacity is
.IR 0 .
.SS PARAMETERS
.TP
.IR soe :
the size of the element.
.SH RETURN VALUE
The
.BR zvec_new ()
function return a pointer to the instance.
.SH ERROR
Cause segfault when
.BR malloc ()
returns 
.IR NULL .
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR zvec_new ()
T}	Thread safety	MT-Safe
.TE
.SH EXAMPLE
// Create a vector of integers.
.br
.BI "zvec_t* " ivec " = zvec_new(sizeof(" int "));
.SH SEE ALSO
.TP
.BR malloc (3)
the allocation method.
.TP
.BR zvec_free (3)
free the resources referred by the instance.
.TP
.BR zvec_from (3)
create vector from C array.
.TP
.BR zvec_slice (3)
create sub-vector from existing one.
