name: ZC CI

on:
  push:
    branches: [ aloof ]
  pull_request:
    branches: [ aloof ]
  schedule:
    - cron: '29 11 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: ztest
      run: ./ztest
